// Sementes de reviews do dataset offline, organizadas por arquétipo.
// O gerador expande pra 400 variando nome, data, nota e pequenas mutações de texto.

export const sementesReviews = [
  // ─── genérica 5 estrelas (vaga, podia ser sobre qualquer coisa) ───
  { tipo: 'generica5', texto: 'Produto muito bom, chegou rápido, recomendo o vendedor.' },
  { tipo: 'generica5', texto: 'Excelente qualidade, superou minhas expectativas.' },
  { tipo: 'generica5', texto: 'Muito bom, igual na foto. Comprem sem medo.' },
  { tipo: 'generica5', texto: 'Ótimo custo benefício, valeu cada centavo.' },
  { tipo: 'generica5', texto: 'Chegou bem embalado e antes do prazo. Nota 10.' },
  { tipo: 'generica5', texto: 'Top demais, já é minha segunda compra.' },
  { tipo: 'generica5', texto: 'Perfeito, exatamente como descrito no anúncio.' },
  { tipo: 'generica5', texto: 'Amei, comprarei mais vezes dessa loja.' },
  { tipo: 'generica5', texto: 'Muito satisfeito com a compra, vendedor atencioso.' },
  { tipo: 'generica5', texto: 'Recomendo, produto de qualidade e entrega ok.' },
  { tipo: 'generica5', texto: 'Cumpre o que promete, sem mais.' },
  { tipo: 'generica5', texto: 'Presenteei minha mãe e ela gostou muito.' },
  { tipo: 'generica5', texto: 'Bonito, barato e funcional. O que mais pedir?' },
  { tipo: 'generica5', texto: 'Melhor compra que fiz esse ano com certeza.' },
  { tipo: 'generica5', texto: 'Veio tudo certinho, conferido e aprovado.' },
  { tipo: 'generica5', texto: 'Qualidade surpreendente pelo preço pago.' },
  { tipo: 'generica5', texto: 'Já testei e funciona perfeitamente, obrigado.' },
  { tipo: 'generica5', texto: 'Loja confiável, produto original, entrega rápida.' },
  { tipo: 'generica5', texto: 'Simplesmente perfeito, sem defeitos.' },
  { tipo: 'generica5', texto: 'Gostei muito, uso todos os dias.' },
  { tipo: 'generica5', texto: 'Atendeu perfeitamente a necessidade, recomendo.' },
  { tipo: 'generica5', texto: 'Produto fiel às fotos, muito bem feito.' },
  { tipo: 'generica5', texto: 'Ótima compra, mereceu as 5 estrelas.' },
  { tipo: 'generica5', texto: 'Tudo certo, como sempre. Cliente antigo da loja.' },
  { tipo: 'generica5', texto: 'Muito prático, deveria ter comprado antes.' },
  { tipo: 'generica5', texto: 'Chegou em perfeito estado, bem protegido.' },
  { tipo: 'generica5', texto: 'Recomendo de olhos fechados, ótimo produto.' },
  { tipo: 'generica5', texto: 'Excelente, minha esposa aprovou.' },
  { tipo: 'generica5', texto: 'Não tenho do que reclamar, tudo perfeito.' },
  { tipo: 'generica5', texto: 'Produto bom e bonito, papelaria caprichada.' },

  // ─── claramente sobre outro produto ───
  { tipo: 'produtoErrado', texto: 'A estampa da camiseta é linda, tecido um pouco fino mas vale o preço.' },
  { tipo: 'produtoErrado', texto: 'O sabor de morango é o melhor, minha filha adorou.' },
  { tipo: 'produtoErrado', texto: 'Serviu perfeitamente no meu pulso, pulseira confortável.' },
  { tipo: 'produtoErrado', texto: 'A frigideira não gruda nada, ovo desliza que é uma beleza.' },
  { tipo: 'produtoErrado', texto: 'Ficou ótimo na parede da sala, combinou com o sofá.' },
  { tipo: 'produtoErrado', texto: 'Meu cachorro amou o sabor de frango, compro sempre.' },
  { tipo: 'produtoErrado', texto: 'As rodinhas giram muito bem, mala excelente pra viagem.' },
  { tipo: 'produtoErrado', texto: 'Comprei o tamanho 42 e serviu certinho, tênis confortável.' },
  { tipo: 'produtoErrado', texto: 'O cheiro é maravilhoso, fixação dura o dia todo.' },
  { tipo: 'produtoErrado', texto: 'Livro chegou sem amassados, história envolvente.' },
  { tipo: 'produtoErrado', texto: 'A cor do batom é igual da foto, super pigmentado.' },
  { tipo: 'produtoErrado', texto: 'Instalei no meu carro e o som ficou muito melhor.' },
  { tipo: 'produtoErrado', texto: 'As sementes germinaram em uma semana, recomendo.' },
  { tipo: 'produtoErrado', texto: 'Ótimo colchão, minhas costas agradecem.' },
  { tipo: 'produtoErrado', texto: 'A capinha encaixou perfeita no meu celular, linda.' },
  { tipo: 'produtoErrado', texto: 'Panela de pressão excelente, feijão em 15 minutos.' },

  // ─── reclamação de frete ───
  { tipo: 'freteAtrasado', texto: 'Demorou 3 meses pra chegar, já tinha até esquecido que comprei.' },
  { tipo: 'freteAtrasado', texto: 'O produto é bom mas o frete demorou demais, quase 2 meses.' },
  { tipo: 'freteAtrasado', texto: 'Rastreamento ficou parado 40 dias em Curitiba. Chegou, mas a paciência não.' },
  { tipo: 'freteAtrasado', texto: 'Comprei pro Natal e chegou no Carnaval. Sem condições.' },
  { tipo: 'freteAtrasado', texto: 'A entrega atrasou tanto que comprei outro na loja física. Agora tenho dois.' },
  { tipo: 'freteAtrasado', texto: 'Nunca mais compro, esperei 84 dias e veio amassado.' },
  { tipo: 'freteAtrasado', texto: 'O rastreio dizia entregue mas só chegou 3 semanas depois. Estranho.' },
  { tipo: 'freteAtrasado', texto: 'Pedido ficou preso na alfândega e ainda paguei taxa. Revoltado.' },
  { tipo: 'freteAtrasado', texto: 'Frete grátis porém eterno. Escolha o seu sofrimento.' },
  { tipo: 'freteAtrasado', texto: 'Chegou depois de 71 dias. O produto até que é bom, mas nossa.' },
  { tipo: 'freteAtrasado', texto: 'Meu filho cresceu esperando o brinquedo chegar. Serviu no irmão mais novo.' },
  { tipo: 'freteAtrasado', texto: 'Vendedor simpático mas a transportadora fez turismo com meu pacote pelo Brasil inteiro.' },

  // ─── português de tradução automática ───
  { tipo: 'traducaoRuim', texto: 'O produto muito bom de usar. Estou satisfeito para a compra feliz.' },
  { tipo: 'traducaoRuim', texto: 'Chegou o pacote com rapidez de navio veloz. Obrigado vendedor amigo.' },
  { tipo: 'traducaoRuim', texto: 'Qualidade de bom preço. A esposa dela gostou muito do presente que dei ela.' },
  { tipo: 'traducaoRuim', texto: 'Funciona conforme o esperado da expectativa. Recomendo para todos os humanos.' },
  { tipo: 'traducaoRuim', texto: 'Muito bom o material de plástico de qualidade de metal.' },
  { tipo: 'traducaoRuim', texto: 'O dente azul conecta rápido no telefone portátil. Som de ouvido bonito.' },
  { tipo: 'traducaoRuim', texto: 'Recebi em casa minha com sucesso de entrega. Cinco estrela para loja.' },
  { tipo: 'traducaoRuim', texto: 'A cor veio igual da fotografia de imagem. Bonito de ver com os olhos.' },
  { tipo: 'traducaoRuim', texto: 'Produto chegou de bem embalado na caixa de papel forte. Gostei do conteúdo interior.' },
  { tipo: 'traducaoRuim', texto: 'Usando todos os dias da semana e alguns do mês. Funcionamento correto.' },
  { tipo: 'traducaoRuim', texto: 'Boa compra de dinheiro bem gastado. Voltarei para comprar o retorno.' },
  { tipo: 'traducaoRuim', texto: 'O tamanho serve no tamanho certo. Veste bom no corpo da pessoa.' },
  { tipo: 'traducaoRuim', texto: 'Superou a expectativa que eu esperava esperar. Parabéns fábrica.' },
  { tipo: 'traducaoRuim', texto: 'Ele liga quando aperta o botão de ligar. Tecnologia impressionante de moderna.' },
  { tipo: 'traducaoRuim', texto: 'Presente para o filho do meu filho. A criança neto ficou alegria.' },
  { tipo: 'traducaoRuim', texto: 'Muito satisfação. O produto faz a função da sua funcionalidade.' },

  // ─── 5 estrelas com texto devastador ───
  { tipo: 'cincoDevastador', texto: 'Quebrou no segundo dia de uso, plástico horroroso, cheiro forte de química. Não recomendo.' },
  { tipo: 'cincoDevastador', texto: 'Veio faltando peça, o vendedor não responde e a cor é diferente do anúncio. Péssimo.' },
  { tipo: 'cincoDevastador', texto: 'Pior compra da minha vida, parou de funcionar em uma semana e ainda esquentava muito.' },
  { tipo: 'cincoDevastador', texto: 'Menor do que parece na foto, frágil e veio riscado. Dinheiro jogado fora.' },
  { tipo: 'cincoDevastador', texto: 'Não funciona como prometido, o botão travou no terceiro uso. Decepcionante.' },
  { tipo: 'cincoDevastador', texto: 'Horrível. Minha filha chorou quando viu. Nada a ver com as fotos.' },
  { tipo: 'cincoDevastador', texto: 'O cheiro de plástico queimado não sai nem lavando. Usei duas vezes e joguei fora.' },
  { tipo: 'cincoDevastador', texto: 'Derreteu no sol do carro. Nunca vi material tão vagabundo, sério.' },
  { tipo: 'cincoDevastador', texto: 'A costura desfez na primeira semana e o zíper enferrujou. Qualidade zero.' },
  { tipo: 'cincoDevastador', texto: 'Comprei duas unidades, as duas com defeito diferente. Impressionante a consistência.' },
  { tipo: 'cincoDevastador', texto: 'Não carrega, não liga, não presta. Fora a demora pra chegar.' },
  { tipo: 'cincoDevastador', texto: 'Rasgou no primeiro uso e manchou minha roupa. Experiência terrível do início ao fim.' },

  // ─── detalhe estranhamente específico ───
  { tipo: 'detalheEstranho', texto: 'Funciona bem mas emite um apito que só meu cachorro escuta. Ele odeia o produto.' },
  { tipo: 'detalheEstranho', texto: 'Comprei pra minha sogra e agora ela vem mais vezes aqui em casa. Avaliem vocês.' },
  { tipo: 'detalheEstranho', texto: 'O manual vem em 6 idiomas e nenhum é português. Aprendi um pouco de turco.' },
  { tipo: 'detalheEstranho', texto: 'Veio com um bilhete escrito à mão pedindo 5 estrelas em troca de cupom. Deu certo.' },
  { tipo: 'detalheEstranho', texto: 'É idêntico ao da minha vizinha que pagou o triplo na loja. Não contei pra ela.' },
  { tipo: 'detalheEstranho', texto: 'O cheiro lembra a casa da minha avó em 1997. Compraria de novo só por isso.' },
  { tipo: 'detalheEstranho', texto: 'Uso para um propósito completamente diferente do anunciado e funciona perfeitamente.' },
  { tipo: 'detalheEstranho', texto: 'A caixa veio com 3 parafusos extras que não servem em lugar nenhum. Guardei por precaução.' },
  { tipo: 'detalheEstranho', texto: 'Meu papagaio aprendeu a imitar o som que ele faz ao ligar. Agora nunca sei qual dos dois é.' },
  { tipo: 'detalheEstranho', texto: 'Comprei bêbado numa promoção relâmpago às 3 da manhã. Melhor decisão que já tomei nesse estado.' },
  { tipo: 'detalheEstranho', texto: 'A luzinha azul pisca a noite toda tipo farol. Meu quarto parece balada agora. Gostei.' },
  { tipo: 'detalheEstranho', texto: 'Terceira unidade que compro. As outras duas estão em algum lugar da casa.' },
  { tipo: 'detalheEstranho', texto: 'Veio um adesivo de sorriso dentro da caixa. Colei na geladeira. O produto também é bom.' },
  { tipo: 'detalheEstranho', texto: 'Idêntico à foto, o que me assustou. Nunca tinha acontecido isso antes nessa loja.' },

  // ─── tamanho ou cor errada ───
  { tipo: 'tamanhoErrado', texto: 'Pedi preto e veio azul marinho escuro quase preto. Fiquei com ele mesmo assim.' },
  { tipo: 'tamanhoErrado', texto: 'A tabela de medidas mente. Pedi G e veio um PP com etiqueta de G.' },
  { tipo: 'tamanhoErrado', texto: 'Muito menor do que parece na foto. Tipo, muito menor. Cabe na palma da mão.' },
  { tipo: 'tamanhoErrado', texto: 'Pedi rosa e veio vermelho. A loja disse que é rosa escuro. Não é.' },
  { tipo: 'tamanhoErrado', texto: 'Serviria no meu filho de 8 anos, mas comprei pra mim. Doei pra ele então.' },
  { tipo: 'tamanhoErrado', texto: 'O 42 deles é o 39 do Brasil. Comprem 3 números acima, confia.' },
  { tipo: 'tamanhoErrado', texto: 'Na foto parece grande, chegou do tamanho de um chaveiro. Reli o anúncio: 1:12 escala. Erro meu.' },
  { tipo: 'tamanhoErrado', texto: 'Veio dourado em vez de prateado. Até combinou mais, mas avisem né.' },
  { tipo: 'tamanhoErrado', texto: 'A cor da foto é vibrante, a real é pastel desbotado. Bonito, mas outro produto.' },
  { tipo: 'tamanhoErrado', texto: 'Apertado no braço, folgado no punho. Anatomia de outro planeta.' },
]
